### ISSUE TITLE
Batch Endpoint not Caught

### ISSUE THREAD

**Issue by TheSench** [DP6/roger-watcher#16]
When requests are sent in batches via the google-analytics.com/batch endpoint, they are not caught by the plugin.

**Comment by joaquimsn** [comment]
@TheSench thank you for pointing out this problem, it is already being analyzed for correction.

**Comment by TheSench** [comment]
I know of at least the following two tweaks that need to be made:
1. Add the `/batch` endpoints [here](https://github.com/DP6/roger-watcher/blob/master/src/js/script.js#L243-L247)
2. Add the following additional processing [here](https://github.com/DP6/roger-watcher/blob/master/src/js/script.js#L219) to process the individual requests separately:
```javascript
.map(row => row.split('\n'))
.flat()
```

**Comment by TheSench** [comment]
The following regex statements also need to be updated to handle `/batch` instead of `/collect?{queryString}`:
https://github.com/DP6/roger-watcher/blob/master/src/js/rules.js#L4

Making these changes appears to get batch collection working.

**Comment by TheSench** [comment]
I can throw up a PR later when I get the time.
